### ISSUE TITLE
Incorrect documentation on how "张衡路窝里斗大学一楼食堂彻底完蛋啦" solved retter

### ISSUE THREAD

**Issue by Rotera** [zsxsoft/my-ctf-challenges#1]
FYI I didn't try to bypass the hook detection. I used something more similar to [this](https://stackoverflow.com/a/43055806).

Basically, you can get the `__webpack_require__` by loading a bogus module, with this it is possible to find a dict of all loaded modules. You may then simply use this as `require`, call `require('./universal/components/Flag.js')` to get a reference to the flag component.

**Comment by zsxsoft** [comment]
I'm sorry for my mistake, thanks for correction!

Maybe we found a new solution and now I'm working on it, then I'll update the readme.

**Comment by zsxsoft** [comment]
Updated, thanks!
